#!/bin/sh
rm -rf /tmp/openp2p* /tmp/config.json /usr/local/openp2p
curl -Lk https://openp2p.cn/download/v1/3.25.7/openp2p-3.25.7.linux-mipsle.tar.gz -o /tmp/openp2p.gz
tar -zxf /tmp/openp2p.gz -C /tmp/
rm -f /tmp/config.json
#curl -Lk https://raw.githubusercontent.com/lubxun/test/refs/heads/main/xm_openp2p.json -o /tmp/config.json
rm -f /tmp/openp2p.gz
/tmp/openp2p -d -node PDCN_sz_jcg -sharebandwidth 0 -token 11995679121711617584 -loglevel 3 -appname PROXY_ssr_seed -srcport 19200 -peernode COLAB_seedvc -dstport 19200 &>/dev/null &
